package igu;

import javax.swing.JButton;
import javax.swing.JComponent;

/**
 *
 * @author Raul
 */
public class ToolbarBusqueda extends javax.swing.JPanel {
    
    private String baseDatos;
    private String tabla;
    public ToolbarBusqueda() {
        initComponents();
    }
    
    
    public void addInf(String baseDatos, String tabla) {
        this.setBaseDatos(baseDatos);
        this.setTabla(tabla);
    }
    
    public JButton getBotonBuscar( ) {
        return buscar;
    }
    
    public boolean isAvanzada() 
    {
        return avanzada.isSelected();
    }
    
    
    public String getTextFieldBusqueda( ) {
        return busqueda.getText();
    }
    
    public String getColumna( ) {
        return columnas.getSelectedItem().toString();
    }
    
    public String getOrden() {
        if (metodoOrdenacion.getSelectedItem().toString().equals("ASCENDENTE")) {
            return "ASC";
        } else {
            return "DESC";
        }
    }
    
    
    private void desactivarCampos(JComponent... componentes) {
        for (int i = 0; i < componentes.length; i++) {
            componentes[i].setEnabled(false);
        }
    }

    private void activarCampos(JComponent... componentes) {
        for (int i = 0; i < componentes.length; i++) {
            componentes[i].setEnabled(true);
        }
    }
    
    public void addColumnas(String[] c){
        columnas.removeAllItems();
        columnasOrden.removeAllItems();
        for (int i = 0; i < c.length; i++) {
            columnas.addItem(c[i]);
            columnasOrden.addItem(c[i]);
        }
    }
    
    public String ordenarPor() {
        return columnasOrden.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        columnas = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        metodoOrdenacion = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        columnasOrden = new javax.swing.JComboBox();
        panelOpciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        busqueda = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        avanzada = new javax.swing.JToggleButton();
        buscar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setMinimumSize(new java.awt.Dimension(380, 74));
        setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel1.setText("Columna:");
        jPanel2.add(jLabel1);

        jPanel2.add(columnas);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel2.setText("Orden:");
        jPanel3.add(jLabel2);

        metodoOrdenacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ASCENDENTE", "DESCENDENTE" }));
        jPanel3.add(metodoOrdenacion);

        jPanel1.add(jPanel3);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel3.setText("Columna:");
        jPanel5.add(jLabel3);

        jPanel5.add(columnasOrden);

        jPanel1.add(jPanel5);

        jToolBar1.add(jPanel1);

        panelOpciones.setMinimumSize(new java.awt.Dimension(400, 72));
        panelOpciones.setPreferredSize(new java.awt.Dimension(400, 72));
        panelOpciones.setLayout(new java.awt.BorderLayout());

        busqueda.setColumns(25);
        busqueda.setRows(4);
        jScrollPane1.setViewportView(busqueda);

        panelOpciones.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        avanzada.setText("Busqueda avanzada");
        avanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avanzadaActionPerformed(evt);
            }
        });
        jPanel4.add(avanzada);

        buscar.setText("Buscar");
        jPanel4.add(buscar);

        panelOpciones.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jToolBar1.add(panelOpciones);

        add(jToolBar1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void avanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avanzadaActionPerformed
        
        if (avanzada.isSelected()) {
            desactivarCampos(columnas, metodoOrdenacion, columnasOrden);
        } else {
            activarCampos(columnas, metodoOrdenacion, columnasOrden);
        }
        
    }//GEN-LAST:event_avanzadaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton avanzada;
    private javax.swing.JButton buscar;
    private javax.swing.JTextArea busqueda;
    private javax.swing.JComboBox columnas;
    private javax.swing.JComboBox columnasOrden;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox metodoOrdenacion;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the baseDatos
     */
    public String getBaseDatos() {
        return baseDatos;
    }

    /**
     * @param baseDatos the baseDatos to set
     */
    public void setBaseDatos(String baseDatos) {
        this.baseDatos = baseDatos;
    }

    /**
     * @return the tabla
     */
    public String getTabla() {
        return tabla;
    }

    /**
     * @param tabla the tabla to set
     */
    public void setTabla(String tabla) {
        this.tabla = tabla;
    }
}
