/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUAN
 */
public class Productos extends javax.swing.JFrame {

    
    //private Connection cnx;
    public String url="jdbc:sqlserver://localhost;databaseName=Abarrotes_P";
    String user="sa";
    String contraseña="1234";
    Connection conn;
    String driver="sun.jdbc.obdc.java";
    
    Conexion Conect;
    ResultSet Datos;
    Statement Sentencias;
    ResultSet rs;
    /**
     * Creates new form Productos
     */
    public Productos() {
        
         
        initComponents();
        
           Codigo.setEnabled(false);
           Producto.setEnabled(false);
           Precio.setEnabled(false);
           Marca.setEnabled(false);
           Eliminar.setEnabled(false);
           Editar.setEnabled(false);
           Nuevo.setEnabled(true);
           Grabar.setEnabled(false);
           Guardar.setEnabled(false);
           Cancelar.setEnabled(false);
           
           if( Loggin.Consultor.isSelected()==true){
                Nuevo.setEnabled(false);
                Codigo.setEnabled(false);
                Producto.setEnabled(false);
           Precio.setEnabled(false);
           Marca.setEnabled(false);
          
           Guardar.setEnabled(false);
           Editar.setEnabled(false);
           Eliminar.setEnabled(false);
           Grabar.setEnabled(false);
           Cancelar.setEnabled(false);
          
           }
           
            if( Loggin.User.isSelected()==true){
                Nuevo.setEnabled(true);
                Codigo.setEnabled(false);
                Producto.setEnabled(false);
           Precio.setEnabled(false);
           Marca.setEnabled(false);
          
           Guardar.setEnabled(false);
           Editar.setEnabled(false);
           Eliminar.setEnabled(false);
           Grabar.setEnabled(false);
           Cancelar.setEnabled(false);
          
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void Actualizar(){
                
       
       DefaultTableModel modelo = new DefaultTableModel();
        Consultas.setModel(modelo);
       String SQL=("Select * from Productos where Producto like('"+M.getText()+"%')");
       
        try{
           conn = Conexion.crearConexion();
           rs=conn.createStatement().executeQuery(SQL);
           ResultSetMetaData rsm = rs.getMetaData();
           int cantidadColumnas = rsm.getColumnCount();
           
           for(int i=1; i<=cantidadColumnas;i++){
               modelo.addColumn(rsm.getColumnLabel(i));
           }
           while(rs.next()){
               Object[] fila = new Object[cantidadColumnas];
               for(int i=0; i< cantidadColumnas; i++){
                   fila[i]=rs.getObject(i+1);
               }
               modelo.addRow(fila);
           }
           rs.close();
       }catch(Exception e){
           System.out.println("Error"+e);
       }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        M = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Consultas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Producto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Precio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Marca = new javax.swing.JTextField();
        Nuevo = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Grabar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFocusable(false);

        jLabel2.setText("Buscar Producto");

        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });
        M.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MKeyTyped(evt);
            }
        });

        Consultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Precio", "Marca"
            }
        ));
        Consultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Consultas);
        if (Consultas.getColumnModel().getColumnCount() > 0) {
            Consultas.getColumnModel().getColumn(0).setResizable(false);
            Consultas.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Codigo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Producto");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Precio");

        Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Marca");

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Grabar.setText("Grabar");
        Grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrabarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Productos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(Nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Grabar))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(36, 36, 36)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(Marca))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLabel2)
                    .addGap(18, 18, 18)
                    .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Codigo)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        String sentenciaInsert="EXECUTE InsertarProducto "+"'"+this.Codigo.getText().trim()+"','"+this.Producto.getText().trim()+"','"+this.Precio.getText().trim()+"','"+this.Marca.getText().trim()+"'";
        if(Codigo.getText().length()==0 || Producto.getText().length()==0 ||  Precio.getText().length()==0 || Marca.getText().length()==0 ){
            JOptionPane.showMessageDialog(null,"Campos vacios");
        }
        else{
       try{
           conn=DriverManager.getConnection(url,user,contraseña);
           Statement sentencia= conn.createStatement();
           int numFilas = sentencia.executeUpdate(sentenciaInsert);
           JOptionPane.showMessageDialog(null, numFilas+ " nuevo registro");
           Codigo.setText("");
           Producto.setText("");
           Precio.setText("");
           Marca.setText("");
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
       
       
     
       
        }
        Actualizar();
    }//GEN-LAST:event_GuardarActionPerformed

    private void MKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MKeyPressed
      
        
       
       DefaultTableModel modelo = new DefaultTableModel();
        Consultas.setModel(modelo);
       String SQL=("select * from Productos where Producto like('"+M.getText()+"%')");
       
        try{
            System.out.println("pucha");
           conn = Conexion.crearConexion();
           ResultSet rs;
           rs=conn.createStatement().executeQuery(SQL);
           ResultSetMetaData rsm = rs.getMetaData();
           int cantidadColumnas = rsm.getColumnCount();
            System.out.println("pucha2");
           for(int i=1; i<=cantidadColumnas;i++){
               modelo.addColumn(rsm.getColumnLabel(i));
           }
           while(rs.next()){
               Object[] fila = new Object[cantidadColumnas];
               for(int i=0; i< cantidadColumnas; i++){
                   fila[i]=rs.getObject(i+1);
               }
               modelo.addRow(fila);
           }
           rs.close();
       }catch(Exception e){
           System.out.println("Error"+e);
       }
     
       
      
        
        
    }//GEN-LAST:event_MKeyPressed

    private void ConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultasMouseClicked
        
        if( Loggin.Administrador.isSelected()==true){
        try{
          String m= M.getText();
          int row = Consultas.getSelectedRow();
          String Table_click=(Consultas.getModel().getValueAt(row, 0).toString());
          String SQL=("Execute BuscarCodProducto"+"'"+Table_click+"'");
          conn = Conexion.crearConexion();
           rs=conn.createStatement().executeQuery(SQL);
           
           if(rs.next()){
               String add1=rs.getString("Codigo");
               Codigo.setText(add1);
                String add2=rs.getString("Producto");
               Producto.setText(add2);
                String add3=rs.getString("Precio");
               Precio.setText(add3);
                String add4=rs.getString("Marca");
               Marca.setText(add4);
                
               
           }
           Codigo.setEnabled(false);
           Producto.setEnabled(false);
           Precio.setEnabled(false);
           Marca.setEnabled(false);
           Eliminar.setEnabled(true);
           Editar.setEnabled(true);
           Nuevo.setEnabled(false);
           Cancelar.setEnabled(true);
           
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
          }
        }
        
        if( Loggin.Consultor.isSelected()==true){
        try{
          String m= M.getText();
          int row = Consultas.getSelectedRow();
          String Table_click=(Consultas.getModel().getValueAt(row, 0).toString());
          String SQL=("Execute BuscarCodProducto"+"'"+Table_click+"'");
          conn = Conexion.crearConexion();
           rs=conn.createStatement().executeQuery(SQL);
           
           if(rs.next()){
               String add1=rs.getString("Codigo");
               Codigo.setText(add1);
                String add2=rs.getString("Producto");
               Producto.setText(add2);
                String add3=rs.getString("Precio");
               Precio.setText(add3);
                String add4=rs.getString("Marca");
               Marca.setText(add4);
                
               
           }
           Nuevo.setEnabled(false);
                Codigo.setEnabled(false);
                Producto.setEnabled(false);
           Precio.setEnabled(false);
           Marca.setEnabled(false);
          
           Guardar.setEnabled(false);
           Editar.setEnabled(false);
           Eliminar.setEnabled(false);
           Grabar.setEnabled(false);
           Cancelar.setEnabled(false);
           
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
          }
        }
        
        if( Loggin.User.isSelected()==true){
        try{
          String m= M.getText();
          int row = Consultas.getSelectedRow();
          String Table_click=(Consultas.getModel().getValueAt(row, 0).toString());
          String SQL=("Execute BuscarCodProducto"+"'"+Table_click+"'");
          conn = Conexion.crearConexion();
           rs=conn.createStatement().executeQuery(SQL);
           
           if(rs.next()){
               String add1=rs.getString("Codigo");
               Codigo.setText(add1);
                String add2=rs.getString("Producto");
               Producto.setText(add2);
                String add3=rs.getString("Precio");
               Precio.setText(add3);
                String add4=rs.getString("Marca");
               Marca.setText(add4);
                        
          }
           Nuevo.setEnabled(false);
                Codigo.setEnabled(false);
                Producto.setEnabled(false);
           Precio.setEnabled(false);
           Marca.setEnabled(false);
          
           Guardar.setEnabled(false);
           Editar.setEnabled(false);
           Eliminar.setEnabled(false);
           Grabar.setEnabled(false);
           Cancelar.setEnabled(false);
          
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
          }
        }
    }//GEN-LAST:event_ConsultasMouseClicked

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
           
           Codigo.setText("");
           Producto.setText("");
           Precio.setText("");
           Marca.setText("");
        
           Codigo.setEnabled(true);
           Producto.setEnabled(true);
           Precio.setEnabled(true);
           Marca.setEnabled(true);
           
           Eliminar.setEnabled(false);
           Editar.setEnabled(false);
           Nuevo.setEnabled(true);
           Grabar.setEnabled(false);
           Guardar.setEnabled(true);
           Cancelar.setEnabled(false);
    }//GEN-LAST:event_NuevoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
         String sentenciaInsert="EXECUTE BorrarProducto"+"'"+this.Codigo.getText().trim()+"'";
        if(Codigo.getText().length()==0 || Producto.getText().length()==0 ||  Precio.getText().length()==0 || Marca.getText().length()==0 ){
            JOptionPane.showMessageDialog(null,"Campos vacios");
        }
        else{
       try{
           conn=DriverManager.getConnection(url,user,contraseña);
           Statement sentencia= conn.createStatement();
           int numFilas = sentencia.executeUpdate(sentenciaInsert);
           JOptionPane.showMessageDialog(null, numFilas+ " Registro Eliminado");
           Codigo.setText("");
           Producto.setText("");
           Precio.setText("");
           Marca.setText("");
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
     
        }
        Actualizar();
    }//GEN-LAST:event_EliminarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
         
           Codigo.setEnabled(false);
           Producto.setEnabled(true);
           Precio.setEnabled(true);
           Marca.setEnabled(true);
           Grabar.setEnabled(true);
           Eliminar.setEnabled(false);
           Nuevo.setEnabled(false);
           
    }//GEN-LAST:event_EditarActionPerformed

    private void GrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrabarActionPerformed
       String sentenciaInsert="EXECUTE ModificarProducto "+"'"+this.Codigo.getText().trim()+"','"+this.Producto.getText().trim()+"','"+this.Precio.getText().trim()+"','"+this.Marca.getText().trim()+"'";
        if(Codigo.getText().length()==0 || Producto.getText().length()==0 ||  Precio.getText().length()==0 || Marca.getText().length()==0 ){
            JOptionPane.showMessageDialog(null,"Campos vacios");
        }
        else{
       try{
           conn=DriverManager.getConnection(url,user,contraseña);
           Statement sentencia= conn.createStatement();
           int numFilas = sentencia.executeUpdate(sentenciaInsert);
           JOptionPane.showMessageDialog(null, numFilas+ " Registro modificado");
           Codigo.setText("");
           Producto.setText("");
           Precio.setText("");
           Marca.setText("");
           
           Codigo.setEnabled(false);
           Producto.setEnabled(false);
           Precio.setEnabled(false);
           Marca.setEnabled(false);
           Eliminar.setEnabled(false);
           Editar.setEnabled(false);
           Nuevo.setEnabled(true);
           Grabar.setEnabled(false);
           Guardar.setEnabled(false);
           Cancelar.setEnabled(false);
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
       
        } 
        Actualizar();
    }//GEN-LAST:event_GrabarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
         this.dispose();
         Principal p1=new Principal();
         p1.setVisible(true);
    }//GEN-LAST:event_SalirActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
          Codigo.setText("");
           Producto.setText("");
           Precio.setText("");
           Marca.setText("");
            Eliminar.setEnabled(false);
           Editar.setEnabled(false);
           Nuevo.setEnabled(true);
           Grabar.setEnabled(false);
           Guardar.setEnabled(true);
           Cancelar.setEnabled(false);
           
    }//GEN-LAST:event_CancelarActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MActionPerformed

    private void MKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MKeyTyped
    // TODO add your handling code here:
    }//GEN-LAST:event_MKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTable Consultas;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Grabar;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField M;
    private javax.swing.JTextField Marca;
    private javax.swing.JButton Nuevo;
    private javax.swing.JTextField Precio;
    private javax.swing.JTextField Producto;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
